# .github/workflows/deploy-dev.yml
name: Deploy to Dev

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: SolidBaseTemplate

    steps:
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup Google Cloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # Load the private key (the one whose PUBLIC half is added as a Deploy Key in GitHub)
      - name: Start SSH agent and add GitHub key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.GH_DEPLOY_KEY }}

      - name: Deploy to Dev VM
        run: |
          gcloud compute ssh ${{ secrets.DEV_VM_SSH_USER }}@${{ secrets.DEV_VM_NAME }} \
            --zone=${{ secrets.DEV_VM_ZONE }} \
            --ssh-flag="-A" \
            --command="
              set -euo pipefail
              cd ${{ secrets.DEV_APP_DIRECTORY }} &&
              git fetch origin &&
              git reset --hard HEAD &&
              git checkout ${{ github.ref_name }} &&
              git reset --hard origin/${{ github.ref_name }} &&
              ./scripts/deploy/deploy.sh dev
            "

      - name: Deployment Summary
        run: |
          echo '✅ Deployment completed successfully!'
          echo '📁 Deployed from branch: ${{ github.ref_name }}'
          echo '📁 Deployed to: ${{ secrets.DEV_APP_DIRECTORY }}'
